# ============================================================================
# Sagewood Theme for mpv

# Main mpv options
background-color='#2d3833'
osd-back-color='#222a26'
osd-border-color='#222a26'
osd-color='#d2ded7'
osd-shadow-color='#2d3833'

# Stats script options
# Note: Stats script uses #BBGGRR format
script-opts-append=stats-border_color=262a22
script-opts-append=stats-font_color=d7ded2
script-opts-append=stats-plot_bg_border_color=b3a78d
script-opts-append=stats-plot_bg_color=262a22
script-opts-append=stats-plot_color=b3a78d

# External script options

# UOSC options
script-opts-append=uosc-color=foreground=8da7b3,foreground_text=222a26,background=2d3833,background_text=d2ded7,curtain=222a26,success=a8b59b,error=d99c82
